[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "node"
path = "src/main.rs"

[dependencies]
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sp-io = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-cli = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-executor = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-service = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-network = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { version = "0.8", git = "https://github.com/paritytech/substrate.git" }
grandpa = { version = "2.0.0", package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate.git" }
grandpa-primitives = { version = "2.0.0", package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate.git" }
sc-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-basic-authority = { git = "https://github.com/paritytech/substrate.git" }

node-template-runtime = { version = "2.0.0", path = "./runtime" }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { version = "2.0.0", package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate.git" }
