[workspace]
members = [
	"node",
	"pallets/merkle",
	"pallets/mixer",
	"runtime",
]

[profile.dev.package]
aes-soft = { opt-level = 3 }
aesni = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crossbeam-queue = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
h2 = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

[patch.crates-io]
fork-tree = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-executive = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-metadata = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-support-procedural = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-support-procedural-tools = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-support-procedural-tools-derive = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-assets = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-authorship = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-contracts = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-contracts-proc-macro = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-democracy = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-identity = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-im-online = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-multisig = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-offences = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-proxy = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-recovery = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-session = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-utility = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
pallet-vesting = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-block-builder = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-chain-spec-derive = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-cli = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-client-db = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-executor = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-executor-common = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-executor-wasmi = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-executor-wasmtime = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-informant = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-light = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-network-gossip = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-offchain = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-peerset = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-proposer-metrics = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-rpc-server = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-service = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-state-db = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-telemetry = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-transaction-graph = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-allocator = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-api-proc-macro = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-authorship = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-chain-spec = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-consensus-vrf = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-database = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-debug-derive = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-npos-elections-compact = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-panic-handler = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-sandbox = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-serializer = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-session = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-staking = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-storage = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-tasks = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-trie = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-utils = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-version = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
substrate-browser-utils = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
substrate-frame-cli = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
substrate-test-client = { git = "https://github.com/paritytech/substrate.git", branch = "frontier" }
