[package]
name = "pure-zk"
version = "0.1.0"
authors = ["drewstone <drewstone329@gmail.com>"]
edition = "2018"


[dependencies]
byteorder = { version = "1", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
rand = { version = "0.4", default-features = false }
serde = { version = "1.0.101", optional = true }
serde_derive = { version = "1.0", optional = true }

# substrate modules
support = { package ="frame-support", git = "https://github.com/paritytech/substrate.git", default-features = false }
system = { package ="frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
balances = { package ="pallet-balances", git = "https://github.com/paritytech/substrate.git", default-features = false }

# substrate packages
sr-primitives = { git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate.git", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git", default-features = false }

# crypto packages
bellman-verifier = { git = "https://github.com/LayerXcom/zero-chain.git", default-features = false }
jubjub = { git = "https://github.com/LayerXcom/zero-chain.git", default-features = false }
pairing = { package = "zerochain-pairing", git = "https://github.com/LayerXcom/zero-chain.git", default-features = false }

[dev-dependencies]
primitives = { package = "substrate-primitives",  git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sr-primitives/std",
	"support/std",
	"system/std",
	"balances/std",
	"runtime-io/std",
	"rstd/std",
    "pairing/std",
    "jubjub/std",
]
