[package]
name = "wasm-utils"
version = "0.1.0"
authors = ["Commonwealth <https://github.com/hicommonwealth>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = {version = "0.2.69", features = ["serde-serialize"]}
curve25519-dalek = "3.0.0"
pallet-merkle = { path = "../pallets/merkle" }
rand_core = { version = "0.5", default-features = false, features = ["alloc", "getrandom"] }

[lib]
crate-type = ["cdylib", "rlib"]