[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
edition = "2018"
homepage = "https://substrate.dev"
license = "Unlicense"
name = "node-template-runtime"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "2.0.0" }

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[dependencies]
hex-literal = { optional = true, version = "0.3.1" }
serde = { features = ["derive"], optional = true, version = "1.0.101" }
static_assertions = "1.1.0"

merkle = { package = "pallet-merkle", version = "3.0.0", default-features = false, path = "../pallets/merkle" }
mixer = { package = "pallet-mixer", version = "3.0.0", default-features = false, path = "../pallets/mixer" }
tokens = { package = "pallet-tokens", version = "3.0.0", default-features = false, path = "../pallets/tokens" }
merkle-rpc = { package = "pallet-merkle-rpc", version = "3.0.0", path = "../pallets/merkle/rpc", optional = true }

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-executive = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-support = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system-benchmarking = { default-features = false, optional = true, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system-rpc-runtime-api = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-aura = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-balances = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-contracts = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-contracts-primitives = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-contracts-rpc-runtime-api = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

pallet-evm = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master", default-features = false, optional = true }
pallet-ethereum = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master", optional = true }
fp-rpc = { default-features = false, git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master", optional = true }
pallet-evm-precompile-simple = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master", default-features = false, optional = true }

pallet-grandpa = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-randomness-collective-flip = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-sudo = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-timestamp = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-api = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { default-features = false, version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-core = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-offchain = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-session = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-std = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-version = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

orml-currencies = { version = "0.4.0", default-features = false }
orml-traits = { version = "0.4.0", default-features = false }

[features]
default = ["std", "frontier"]
runtime-benchmarks = [
    "hex-literal",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "merkle/runtime-benchmarks",
	"mixer/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]

frontier = [
    "fp-rpc/std",
    "pallet-ethereum/std",
    "pallet-evm/std",
    "pallet-evm-precompile-simple/std",
]

std = [
    "codec/std",
    "serde",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-aura/std",
    "pallet-balances/std",
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts-rpc-runtime-api/std",
    "pallet-grandpa/std",
    "pallet-randomness-collective-flip/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "merkle/std",
    "merkle-rpc",
    "mixer/std",
    "tokens/std",
]
