[package]
name = "node-template-runtime"
version = "2.0.0-rc2"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

aura = { version = "2.0.0-rc2", default-features = false, package = "pallet-aura", git = "https://github.com/paritytech/substrate.git" }
balances = { version = "2.0.0-rc2", default-features = false, package = "pallet-balances", git = "https://github.com/paritytech/substrate.git" }
frame-support = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
grandpa = { version = "2.0.0-rc2", default-features = false, package = "pallet-grandpa", git = "https://github.com/paritytech/substrate.git" }
randomness-collective-flip = { version = "2.0.0-rc2", default-features = false, package = "pallet-randomness-collective-flip", git = "https://github.com/paritytech/substrate.git" }
sudo = { version = "2.0.0-rc2", default-features = false, package = "pallet-sudo", git = "https://github.com/paritytech/substrate.git" }
system = { version = "2.0.0-rc2", default-features = false, package = "frame-system", git = "https://github.com/paritytech/substrate.git" }
timestamp = { version = "2.0.0-rc2", default-features = false, package = "pallet-timestamp", git = "https://github.com/paritytech/substrate.git" }
transaction-payment = { version = "2.0.0-rc2", default-features = false, package = "pallet-transaction-payment", git = "https://github.com/paritytech/substrate.git" }
frame-executive = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", default-features = false, version = "2.0.0-rc2"}
sp-consensus-aura = { version = "0.8.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", default-features = false, version = "2.0.0-rc2"}
sp-io = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-offchain = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-session = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-std = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-version = { version = "2.0.0-rc2", default-features = false, git = "https://github.com/paritytech/substrate.git" }

clsag = { package = "pallet-clsag", version = "2.0.0", default-features = false, path = "../pallets/clsag" }
merkle = { package = "pallet-merkle", version = "2.0.0", default-features = false, path = "../pallets/merkle" }


[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"aura/std",
	"balances/std",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"grandpa/std",
	"randomness-collective-flip/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sudo/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
	"clsag/std",
	"merkle/std",
]
