[package]
name = "node-template-runtime"
version = "2.0.0-rc6"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

pallet-aura = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-balances = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-support = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-grandpa = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-randomness-collective-flip = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-sudo = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-system = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-timestamp = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-executive = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { default-features = false, version = "2.0.0-rc6", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { version = "0.8.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { default-features = false, version = "2.0.0-rc6", git = "https://github.com/paritytech/substrate.git" }
sp-offchain = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-session = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-std = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-version = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }

clsag = { package = "pallet-clsag", version = "2.0.0", default-features = false, path = "../pallets/clsag" }
merkle = { package = "pallet-merkle", version = "2.0.0", default-features = false, path = "../pallets/merkle" }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"clsag/std",
	"merkle/std",
]
