version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.50-browsers
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/anon

    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          cargo --version
          node --version
          java --version
          google-chrome --version
      - run: ~/anon/scripts/init.sh
      - run: source ~/.cargo/env && ~/anon/scripts/test.sh
      - run: source ~/.cargo/env && ~/anon/scripts/build.sh
orbs:
  browser-tools: circleci/browser-tools@1.1
