version: 2
jobs:
  build:
    docker:
      - image: phusion/baseimage:0.11
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/anon

    steps:
      - checkout
      - run: ~/anon/scripts/init.sh
      - run: source ~/.cargo/env && ~/anon/scripts/test.sh
      - run: source ~/.cargo/env && ~/anon/scripts/bench.sh
      - run: source ~/.cargo/env && ~/anon/scripts/build.sh
      - run: ~/anon/scripts/start.sh >/dev/null 2>&1 & source ~/.cargo/env && ~/anon/scripts/client.sh