version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:13.12-browser"
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/anon

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: ~/anon/scripts/init.sh
      - run: source ~/.cargo/env && ~/anon/scripts/test.sh
      - run: source ~/.cargo/env && ~/anon/scripts/bench.sh
      - run: source ~/.cargo/env && ~/anon/scripts/build.sh
orbs:
  browser-tools: circleci/browser-tools@1.1.1
