[package]
authors = ["drew@commonwealth.im"]
edition = "2018"
name = "pallet-merkle"
version = "2.0.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = "1.0.0" }
balances = { version = "2.0.0", default-features = false, package = "pallet-balances", git = "https://github.com/paritytech/substrate.git" }
frame-support = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-io = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-std = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
merlin = { version = "2.0.0", default-features = false }
rand = { version = "0.7.3", optional = true }
sha2 = { version = "0.9.1", default-features = false }


[dependencies.curve25519-dalek]
# git = "https://github.com/dalek-cryptography/curve25519-dalek"
version = "3.0.0"
default-features = false
features = ["u64_backend", "alloc"]

[dependencies.bencher]
version = "0.1.5"

[dev-dependencies]
sp-core = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"balances/std",
	"safe-mix/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-io/std",
	"rand/std",
]

[[bench]]
name = "bench"
harness = false