[package]
authors = ["Drew Stone <drew@commonwealth.im>, Filip Lazovic"]
description = "Merkle tree membership pallet with zero-knowledge membership proof verification"
edition = "2018"
license = "Unlicense"
name = "pallet-merkle"
version = "2.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "1.3.4"

[dependencies.curve25519-dalek]
version = "3.0.0"
default-features = false
features = ["u64_backend", "alloc"]

[dependencies.bencher]
version = "0.1.5"

[dependencies]
balances = { version = "2.0.0", default-features = false, package = "pallet-balances", git = "https://github.com/paritytech/substrate.git" }
frame-support = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-system = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-std = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
merlin = { version = "2.0.0", default-features = false }
sha2 = { version = "0.9.1", default-features = false }
rand_core = { version = "0.5", default-features = false, features = ["alloc", "getrandom"] }
bulletproofs = { version = "2.0.0", rev = "160c9ab", git = "https://github.com/edgeware-builders/bulletproofs", default-features = false, features = ["yoloproofs"] }
rand = { version = "0.7", optional = true }

[dev-dependencies]
sp-core = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-io = { default-features = false, version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
    "bulletproofs/std",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "rand/std",
    "rand",
]

[[bench]]
name = "bench"
harness = false
