[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2018"
homepage = "https://substrate.dev"
license = "Unlicense"
name = "node-template"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "3.0.0"

[[bin]]
name = "node-template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0" }

[dependencies]
jsonrpc-core = "15.0.0"
structopt = "0.3.8"

# local dependencies
node-template-runtime = { path = "../runtime", version = "3.0.0" }

# Substrate dependencies
frame-benchmarking = { version = "3.0.0" }
frame-benchmarking-cli = { version = "3.0.0" }
pallet-transaction-payment-rpc = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }
sc-cli = { features = ["wasmtime"], version = "0.9.0" }
sc-client-api = { version = "3.0.0" }
sc-consensus = { version = "0.9.0" }
sc-consensus-aura = { version = "0.9.0" }
sc-executor = { features = ["wasmtime"], version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-keystore = { version = "3.0.0" }

sc-rpc = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sc-service = { features = ["wasmtime"], version = "0.9.0" }
sc-transaction-pool = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sp-block-builder = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-consensus = { version = "0.9.0" }
sp-consensus-aura = { version = "0.9.0" }
sp-core = { version = "3.0.0" }
sp-finality-grandpa = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }
substrate-frame-rpc-system = { version = "3.0.0" }

[features]
default = []
runtime-benchmarks = ["node-template-runtime/runtime-benchmarks"]
