[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2018"
homepage = "https://substrate.dev"
license = "Unlicense"
name = "node-template"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "3.0.0"

[[bin]]
name = "node-template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0" }

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
jsonrpc-core = "15.1.0"
jsonrpc-pubsub = "15.0.0"

# local dependencies
node-template-runtime = { path = "../runtime", version = "3.0.0" }

# Substrate dependencies
frame-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-benchmarking-cli = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-cli = { features = ["wasmtime"], version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-chain-spec = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-executor = { features = ["wasmtime"], version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-service = { features = ["wasmtime"], version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }
substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

pallet-contracts-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git" }

fc-consensus = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fp-consensus = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fc-rpc = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fp-rpc = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fc-rpc-core = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fc-db = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
fc-mapping-sync = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }

pallet-evm = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }
pallet-ethereum = { git = "https://github.com/webb-tools/frontier", branch = "drew-frontier-to-master" }

merkle = { package = "pallet-merkle", version = "3.0.0", path = "../pallets/merkle" }
merkle-rpc = { package = "pallet-merkle-rpc", version = "3.0.0", path = "../pallets/merkle/rpc" }

[features]
default = []
runtime-benchmarks = ["node-template-runtime/runtime-benchmarks"]
